### ISSUE TITLE
multi-region support?

### ISSUE THREAD

**Issue by geekdave** [danielfm/aws-limits-exporter#2]
First of all - thanks so much for open sourcing this!  It worked right out of the box and saved me a huge amount of time since I was about to try and implement something similar myself!

I'm using this to monitor trustedadvisor metrics in several regions.  Currently I run multiple instances of this, one-per-region, and use port mapping to give each instance a unique port.  This approach works fine, but it's a bit cumbersome.

Wondering if it would be possible to allow multiple regions to be specified, and exported as a unified set of metrics (of course with the `region` label distinguishing them).

Thanks again!

**Comment by danielfm** [comment]
Thanks, I'm glad you found it useful!

I believe it should be fairly straightforward to change the code to export metrics for multiple regions (probably just launching additional exporters for each extra region [here](https://github.com/danielfm/aws-limits-exporter/blob/f78de3aa1c130c854f26ad48c0a427a39f03cba4/cmd/main.go#L28-L31)), but I did not do that yet because this is not my current use case. Feel free to send a PR though, I'll try to review and merge it as quickly as I can.

**Comment by danielfm** [comment]
I'm not working with AWS anymore so I'm not able to easily test it, but apparently the latest PR #4 is supposed to fix this.

Can you give it a try?
